name: dress_right
description: "Uniform inspection and SRR tracking tool for USAF personnel."
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  provider: ^6.1.1
  flutter_native_splash: ^2.3.6
  flutter_local_notifications: ^19.2.1
  intl: ^0.19.0
  timezone: ^0.10.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  path: ^1.9.0
  file_picker: ^8.1.2
  csv: ^6.0.0
  excel: ^2.1.0
  docx_to_text: ^1.0.1
  uuid: ^4.3.3
  syncfusion_flutter_pdfviewer: ^29.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/wallpapers/
    - assets/wrll/
    - assets/checklists/

flutter_native_splash:
  color: "#000000"
  image: assets/images/dress_right_text.png
  background_image: assets/images/splash_background.png
  android: true
  ios: true
  android_12:
    color: "#000000"
    image: assets/images/dress_right_text.png
    icon_background_color: "#000000"
    branding: null
